<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.automation.training.tests.TravelocityTestsFour" tests="1" time="14.240" ignored="0" failures="1" timestamp="25 may 2020 22:00:11 GMT" skipped="0" hostname="CO-IT005951" errors="0">
  <testcase name="testTravelocity" time="14.240" classname="com.automation.training.tests.TravelocityTestsFour">
    <failure type="org.opentest4j.AssertionFailedError" message="Your partial check-in and check-out dates must fall within your arrival and departure dates. Please review your dates.">
      <![CDATA[org.opentest4j.AssertionFailedError: Your partial check-in and check-out dates must fall within your arrival and departure dates. Please review your dates.
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:48)
	at org.junit.jupiter.api.AssertFalse.assertFalse(AssertFalse.java:54)
	at org.junit.jupiter.api.AssertFalse.assertFalse(AssertFalse.java:37)
	at org.junit.jupiter.api.Assertions.assertFalse(Assertions.java:166)
	at com.automation.training.tests.TravelocityTestsFour.testTravelocity(TravelocityTestsFour.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- testTravelocity -->
</testsuite> <!-- com.automation.training.tests.TravelocityTestsFour -->
